export const FETCH_ALL_MOVIES_START = 'FETCH_ALL_MOVIES_START';
export const FETCH_ALL_MOVIES_SUCCESS = 'FETCH_ALL_MOVIES_SUCCESS';
export const FETCH_ALL_MOVIES_FAIL = 'FETCH_ALL_MOVIES_FAIL';
export const SELECT_MOVIE = 'SELECT_MOVIE';